### PR TITLE
Test mergify

### PR DESCRIPTION
**Pull request by micbou**
# PR Prelude

Thank you for working on YCM! :)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [ ] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [ ] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [ ] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [ ] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

[Please explain **in detail** why the changes in this PR are needed.]

[cont]: https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md
[code]: https://github.com/Valloric/YouCompleteMe/blob/master/CODE_OF_CONDUCT.md

---
This change is [Reviewable](https://reviewable.io/reviews/micbou/youcompleteme/10)

### CODE REVIEW

**Review by micbou — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/micbou/youcompleteme/10#-:-LeDVMQ8B4PX1S9Msn2n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/micbou/youcompleteme/10#-:-LeDXzUuEJ8WvWP_lFKG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bstaletic — APPROVED** [review]
Approved.

**Review by puremourning — APPROVED** [review]
Ok

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/micbou/youcompleteme/10#-:-LeDlNgJ9ZCxkay4WcSv:bnfp4nl)* status: 1 of 2 LGTMs obtained, and 1 stale (waiting on @micbou)

**Review by micbou — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/micbou/youcompleteme/10#-:-LeDmCDnBy_sxD8t7LyS:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained

**Pull request merged**
